### ISSUE TITLE
onplayerjoin için öneriler

### ISSUE THREAD

**Issue by nas0s** [FarukKaradeniz/SpaceHax-client#52]
Aynı ip veya aynı autha sahip kullanıcılar odaya giremesin,

arananlar listesi içindeki bir isim, ip ya da auth odaya giriş yapyığında direkt banlasın.

genel nicklere sahip kullanıcılar(muslera, alex vs) direkt kicklensin

oda içinde o an playerlist içindeki kullanıcı ismiyle giremesin

**Comment by FarukKaradeniz** [comment]
bunu ekleyeceğim, projede geliştirme yaparken kolaylık olması için henüz eklemedim. 
ama genel nicklere sahip kullanıcıları engelleme gibi bişey eklemeyeceğim.

bu issue'yu kapatıyorum
